name: Senpai
description: senpai workflow
inputs:
  gemini_api_key:
    description: Google AI Studio key
    required: true
runs:
  using: composite
  steps:
    - name: Download latest senpai binary
      shell: bash
      run: |
        curl -sSL \
          "https://github.com/${{ github.repository }}/releases/latest/download/senpai" \
          -o senpai
        chmod +x senpai
    - name: Run senpai
      shell: bash
      env:
        GEMINI_API_KEY: ${{ inputs.gemini_api_key }}
      run: ./senpai

